config/routes.rb
Rails.application.routes.draw do
  get "/:channel", to: 'comments#dashboard', as: :dashboard
  root to: 'comments#home'

  # API
  get "/:channel/messages", to: "comments#index", defaults: { format: :json }
  post "/:channel/messages", to: "comments#create", defaults: { format: :json }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :author, presence: true
  validates :content, presence: true
  validates :channel, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :parse_json, only: :create

  def index
    comments = Comment.where(channel: params[:channel]).order('created_at ASC')
    render json: {
      channel: params[:channel],
      messages: comments
    }
  end

  def create
    puts params
    @comment = Comment.new(channel: params[:channel], author: params[:author], content: params[:content])
    if @comment.save
      render json: @comment
    else
      render json: { error: @comment.errors }
    end
  end

  def dashboard
    @comments = Comment.where(channel: params[:channel]).order('created_at ASC')
  end

  def home
    @channels = Comment.all.pluck(:channel).uniq.sort.reverse
  end

  private

  def parse_json
    # Allow students to omit `Content-Type: application/json` in their requests
    begin
      params.merge! ActiveSupport::JSON.decode(request.body.string) if request.body.string.present?
    rescue JSON::ParserError
      # Silently fail if could not parse JSON
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_chatlines.html.erb
<% comments.each do |comment| %>
<tr>
  <td class="date">
    <%= l comment.created_at, format: :short %>
  </td>
  <td class="author">
    <span style="color: #<%= Digest::SHA1.hexdigest(comment.author.downcase)[0, 6] %>">
      <%= comment.author.downcase %>
    </span>
  </td>
  <td class="content">
    <%= comment.content %>
  </td>
</tr>
<% end %>

app/views/comments/dashboard.html.erb
<h1>Chat - <%= params[:channel] %></h1>

<table class="table table-condensed" id="chat">
  <%= render 'chatlines', comments: @comments %>
</table>

<script>
  var DASHBOARD_URL = '<%= dashboard_path(params[:channel], format: :js) %>';
  var COMMENT_COUNT = <%= @comments.size %>;
</script>

app/views/comments/dashboard.js.erb
if (COMMENT_COUNT < <%= @comments.size %>) {
  $('#chat').html('<%= j render 'chatlines', comments: @comments %>');
  $("html, body").animate({ scrollTop: $(document).height() }, 200);
  COMMENT_COUNT = <%= @comments.size %>
}

app/views/comments/home.html.erb
<h1>Wagon Chat API</h1>

<% if @channels.empty? %>
  <p>There are no messages yet</p>
<% else %>
  <ul>
    <% @channels.each do |channel| %>
    <li><%= link_to channel, dashboard_path(channel: channel) %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WagonChatApi</title>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <%= yield %>
    </div>
  </div>
</div>

</body>
</html>